#!/bin/zsh

ORIGIN=`pwd`

for dir in $HOME/rails/*; do
  if [ -d $dir ]; then
    cd $dir

    if [ -f "Rakefile" ]; then
      echo "Cleaning $dir"
      bundle install
      bundle exec rake tmp:clear;
      bundle exec rake log:clear;
      bundle exec rake db:schema:cache:clear;
      bundle exec rake assets:clobber;
    fi
  fi

  cd $HOME
done

cd $ORIGIN
