#!/bin/zsh


HOME=/home/rotsen
BackupDir=$HOME/Dropbox/Backups

DirInHome=(Documentos Escritorio .ssh bins)

cd $HOME
echo `pwd`

for dir in "${DirInHome[@]}"; do
  echo $dir
  tar -c $dir | bzip2 > $BackupDir/$dir.tar.bz2
done


echo "Sincronizando Sql-backups"
rsync -av sql /run/media/rotsen/Hulk/Backup-RotseN
echo "Sincronizando música"
rsync -av Música /run/media/rotsen/Hulk/Backup-RotseN
echo "Sincronizando imágenes"
rsync -av Imágenes Dropbox/Backups --exclude 'backgrounds' --exclude 'Capturas'
echo "Sincronizando desde Dropbox"
rsync -av Dropbox /run/media/rotsen/Hulk/Backup-RotseN
