#!/bin/env bash

# Check if spotfiy is playing and mute the sound if it is not

export XDG_RUNTIME_DIR=/run/user/1000

status=$(dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'PlaybackStatus' 2> /dev/null | grep 'Playing')

if [[ $status == "" ]]; then
  XDG_RUNTIME_DIR=/run/user/1000 amixer -D pulse sset 'Master' "0%" > /dev/null
fi
